[build-system]
requires = ["scikit-build-core>=0.11", "pybind11", "numpy", "polars>=1.37.1"]
build-backend = "scikit_build_core.build"

[project]
name = "respondpy"
version = "0.3.2"
description = "The Syndemic Lab's RESPOND Simulation Python Extension Module."
readme = "README.md"
requires-python = ">=3.11"
authors = [
    { name = "Matthew Carroll", email = "Matthew.Carroll@bmc.org" },
    { name = "Dimitri Baptiste", email = "Dimitri.Baptiste@bmc.org" },
]
maintainers = [
    { name = "Syndemics Lab", email = "Benjamin.Linas@bmc.org" }
]
license = "AGPL-3.0-or-later"
license-files = ["LICENSE.txt"]
keywords = ["simulation", "Opioid Use Disorder", "markov", "Syndemics"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Operating System :: POSIX :: Linux", 
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
    "Typing :: Typed"
]
dependencies = [
    "numpy",
    "polars>=1.37.1"
]

[project.urls]
Homepage = "https://syndemicslab.org"
Documentation = "https://syndemicslab.github.io/respond/"
Repository = "https://github.com/SyndemicsLab/respond.git"
Issues = "https://github.com/SyndemicsLab/respond/issues"

[dependency-groups]
docs = [
    "ipython",
    "myst-parser>=0.13",
    "nbsphinx",
    "sphinx-book-theme>=0.0.33",
    "sphinx>=4.0",
    "sphinx_copybutton",
    "sphinxcontrib-mermaid>=2.1.0",
]
# hypothesis is slow on iOS, can fail health check
# pytest-xdist has no processes on iOS
test = [
    "cloudpickle",
    "mypy>=1.17.1",
    "pylint>=4.0.5",
    "pytest-cov>=7.0.0",
    "pytest>=9.0.2",
    "pytest-benchmark",
    "nox>=2026.2.9",
    "hypothesis>=6.0; sys_platform != 'ios'", 
    "pytest-xdist; sys_platform != 'ios'"
]
github = [
  { include-group = "test" },
  "pytest-github-actions-annotate-failures"
]
dev = [
    { include-group = "test" },
    { include-group = "docs" },
    "cibuildwheel>=2.15.0",
]

[tool.scikit-build]
build.verbose = true
logging.level = "INFO"
minimum-version = "build-system.requires"
cmake.version = ">=3.27.0"
cmake.build-type = "Release"
ninja.version = ">=1.11"
sdist.exclude = [
    ".github/*",
    "docs/*",
    "benchmarks/*",
]
sdist.include = [
    "src/respondpy/_version.py"
]
messages.after-success = "{green}Wheel successfully built"
messages.after-failure = """
{bold.red}Sorry{normal}, build failed. Your platform is {platform.platform}.
"""

[[tool.scikit-build.generate]]
path = "src/respondpy/_version.py"
template = '''
__version__ = version = "${version}"
'''
location = "source"

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true

[tool.pytest]
minversion = "9.0"
testpaths = ["tests", "benchmarks"]
addopts = [
    "-ra",
    "--strict",
    "--import-mode=importlib"
]
filterwarnings = [
    "error",
    "default:could not create cache path:pytest.PytestCacheWarning",
]
log_level = "INFO"
markers = ["smoke", "unit", "integration", "benchmark", "typing"]
required_plugins = ["pytest-benchmark"]

[tool.coverage.run]
omit = ["tests/*", "docs/*", "benchmarks/*", "src/respondpy/_version.py"]

[tool.coverage.report]
exclude_also = [
    "raise AssertionError",
    "raise NotImplementedError",
    "if __name__ == '__main__'"
]
ignore_errors = true

# We only care about type checking the source code
[tool.mypy]
strict = true
ignore_missing_imports = true
warn_unreachable = true
files = ["src/**/*.py", "src/**/*.pyi"]
exclude = ["src/respondpy/_version.py"]
enable_error_code = ["ignore-without-code", "redundant-expr", "truthy-bool"]

[tool.pylint]
py-version = "3.12"
# Shim added to make sure pylint can find our modules since the pybind11 is messing with uv virtual environments. This just adds the src directory to the path before pylint runs but shouldn't impact any distribution details.
init-hook = "import os,sys; sys.path.insert(0, os.path.join(os.getcwd(), 'src'))"
ignore-patterns = ['.*\.pyi']
ignore = "_version.py"
extension-pkg-allow-list = ["respondpy._core"]
reports.output-format = "colorized"
similarities.ignore-imports = "yes"
messages_control.disable = [
  "cyclic-import",
  "fixme",
  "invalid-name",
  "line-too-long",
  "missing-class-docstring",
  "missing-function-docstring",
  "missing-module-docstring",
  "c-extension-no-member",
  "protected-access",
  "too-few-public-methods",
  "too-many-arguments",
  "too-many-branches",
  "too-many-lines",
  "too-many-locals",
  "too-many-return-statements",
  "too-many-statements",
  "too-many-positional-arguments",
  "wrong-import-position",
  "unused-argument", # Covered by ruff
  "unsubscriptable-object", # Wrongly triggered
]

[tool.ruff.lint]
extend-select = [
  "ARG",         # flake8-unused-arguments
  "B",           # flake8-bugbear
  "C4",          # flake8-comprehensions
  "EXE",         # flake8-executable
  "FURB",        # refurb
  "G",           # flake8-logging-format
  "I",           # isort
  "ICN",         # flake8-import-conventions
  "ISC",         # flake8-implicit-str-concat
  "PD",          # pandas-vet
  "PGH",         # pygrep-hooks
  "PIE",         # flake8-pie
  "PL",          # pylint
  "PT",          # flake8-pytest-style
  "PTH",         # flake8-use-pathlib
  "PYI",         # flake8-pyi
  "TID251",      # flake8-tidy-imports.banned-api
  "RET",         # flake8-return
  "RUF",         # Ruff-specific
  "SIM",         # flake8-simplify
  "T20",         # flake8-print
  "UP",          # pyupgrade
  "YTT",         # flake8-2020
]
ignore = [
  "PLR09",          # Too many X
  "PLR2004",        # Magic value in comparison
  "PT013",          # from pytest import approx is fine
  "PT011",          # pytest.raises too broad
  "PYI034",         # We are returning Self, just generic
]
typing-modules = ["respondpy._core"]
isort.required-imports = ["from __future__ import annotations"]
exclude = ["tests/*", "benchmarks/*", "docs/*"]

[tool.ruff.lint.mccabe]
max-complexity = 13

[tool.ruff.lint.per-file-ignores]
"docs/*" = ["T20"]
"tests/*" = ["T20"]
"benchmarks/*" = ["T20"]
"*.pyi" = ["F401", "TID251"]
"**.ipynb" = ["I002", "E731"]


[tool.cibuildwheel]
# Configuration Details
## Note: We only build for Python 3.11 and above, and only for 64 bit architectures. We also skip PyPy, pyodide, android, iOS and graalPy builds.
build = [
    "cp311-*",
    "cp312-*",
    "cp313-*",
    "cp314-*"
]
skip = [
    "*-win32", 
    "*-pyodide_*",
    "*-android_*",
    "*-ios_*",
]
archs = ["auto64"]
# Build Step Details
build-frontend = "build[uv]"
# Test Step Details
test-groups = ["test"]
test-sources = ["pyproject.toml", "tests"]
test-command = "python -m pytest tests -m \"smoke or unit or integration\""
test-skip = [
  "cp31*-musllinux_*", # Threading test crashes on musllinux
  "cp313*", # polars-runtime-32 has issues with abi3 on 3.13 and above
  "cp314*"  # polars-runtime-32 has issues with abi3 on 3.13 and above
]
environment.PIP_PREFER_BINARY = "1"
environment.UV_PREFER_BINARY = "1"
environment.CMAKE_BUILD_PARALLEL_LEVEL = "4"


[[tool.cibuildwheel.overrides]]
select = ["cp3*-win_arm64"]
inherit.environment = "append"
test-command = "python -m pytest -n 1 --benchmark-disable tests -m \"smoke or unit or integration\""
environment.OMP_NUM_THREADS = "1"
environment.OPENBLAS_NUM_THREADS = "1"
environment.MKL_NUM_THREADS = "1"
environment.NUMEXPR_NUM_THREADS = "1"
environment.POLARS_MAX_THREADS = "1"
