[build-system]
requires = ["scikit-build-core", "pybind11", "eigen", "spdlog"]
build-backend = "scikit_build_core.build"

[project]
name = "respondpy"
version = "0.1.0"
description = "The RESPOND Simulation Python Interface"
readme = "README.md"
requires-python = ">=3.9"
authors = [
    { name = "Matthew Carroll", email = "Matthew.Carroll@bmc.org" },
    { name = "Dimitri Baptiste", email = "Dimitri.Baptiste@bmc.org" },
]
maintainers = [{ name = "Syndemics Lab", email = "Benjamin.Linas@bmc.org" }]
keywords = ["simulation", "Opioid Use Disorder", "Syndemics"]
license = "AGPL-3.0-or-later"
license-files = ["LICENSE.txt", "extern/*/LICENSE.txt"]
dependencies = [
    "build>=1.3.0",
    "cibuildwheel>=2.23.3",
    "numpy",
]

[project.urls]
Homepage = "https://github.com/SyndemicsLab/respond"
Issues = "https://github.com/SyndemicsLab/respond/issues"

[tool.scikit-build]
cmake.version = ">=3.27"
sdist.exclude = [".github/**/*.yml"]
sdist.include = ["src/respondpy/**/*.pyi"]
