################################################################################
## File: data_ops.pyi                                                         ##
## Project: RESPONDSimulationv2                                               ##
## Created Date: 2025-05-20                                                   ##
## Author: Matthew Carroll                                                    ##
## -----                                                                      ##
## Last Modified: 2025-05-20                                                  ##
## Modified By: Matthew Carroll                                               ##
## -----                                                                      ##
## Copyright (c) 2025 Syndemics Lab at Boston Medical Center                  ##
################################################################################

from enum import Enum
import io

import numpy as np


class Dimension(Enum):
    kIntervention = ...
    kOud = ...
    kDemogrpahicCombo = ...


class UtilityType(Enum):
    kMin = ...
    kMult = ...


class WriterType(Enum):
    kInput = ...
    kOutput = ...
    kHistory = ...
    kCost = ...
    kUtilites = ...
    kTotals = ...


class OutputType(Enum):
    kString = ...
    kFile = ...


class History:
    def __init__(self) -> None: ...
    @property
    def state_history(self) -> dict[int, np.ndarray]: ...
    @property
    def overdose_history(self) -> dict[int, np.ndarray]: ...
    @property
    def fatal_overdose_history(self) -> dict[int, np.ndarray]: ...
    @property
    def mortality_history(self) -> dict[int, np.ndarray]: ...
    @property
    def intervention_admission_history(self) -> dict[int, np.ndarray]: ...


class Cost:
    def __init__(self) -> None: ...
    @property
    def perspective(self) -> str: ...
    @property
    def healthcare_cost(self) -> dict[int, np.ndarray]: ...
    @property
    def non_fatal_overdose_cost(self) -> dict[int, np.ndarray]: ...
    @property
    def fatal_overdose_cost(self) -> dict[int, np.ndarray]: ...
    @property
    def pharma_cost(self) -> dict[int, np.ndarray]: ...
    @property
    def treatment_cost(self) -> dict[int, np.ndarray]: ...


def create_matrix3d(x1: int, x2: int, x3: int) -> np.ndarray: ...
def print_matrix3d(matrix: np.ndarray, stream: io.BytesIO) -> None: ...
def print_timed_matrix3d(
    data: dict[int, np.ndarray], stream: io.BytesIO) -> None: ...


def vec_min_matrix3d(data: list[np.ndarray]) -> np.ndarray: ...
def vec_mult_matrix3d(data: list[np.ndarray]) -> np.ndarray: ...
def sum_timed_matrix3d(data: dict[int, np.ndarray]) -> np.ndarray: ...


def sum_timed_matrix3d_over_dimensions(
    data: dict[int, np.ndarray]) -> float: ...


def mult_timed_matrix3d_by_double(
    data: dict[int, np.ndarray], val: float) -> dict[int, np.ndarray]: ...


def mult_timed_matrix3d_by_matrix(
    data: dict[int, np.ndarray], val: np.ndarray) -> dict[int, np.ndarray]: ...


class CostLoader:
    def __init__(self, directory: str, log_name: str) -> None: ...

    def load_healthcare_utilization_cost(
        self, file: str) -> dict[str, np.ndarray]: ...

    def load_overdose_cost(self, file: str) -> dict[str, dict[str, float]]: ...
    def load_pharmaceutical_cost(self, file: str) -> dict[str, np.ndarray]: ...

    def load_treatment_utilization_cost(
        self, file: str) -> dict[str, np.ndarray]: ...

    def get_healthcare_utilization_cost(
        self, perspective: str) -> np.ndarray: ...

    def get_pharmaceutical_cost(self, perspective: str) -> np.ndarray: ...
    def get_treatment_utilization_cost(
        self, perspective: str) -> np.ndarray: ...

    def get_non_fatal_overdose_cost(self, perspective: str) -> float: ...
    def get_fatal_overdose_cost(self, perspective: str) -> float: ...


class DataFormatter:
    def __init__(self, directory: str, log_name: str) -> None: ...

    def extract_timesteps(self, timesteps: list[int], history: History, costs: list[Cost],
                          utilities: dict[int, np.ndarray], cost_switch: bool) -> None: ...


class DataLoader:
    def __init__(self, directory: str, log_name: str) -> None: ...
    def get_initial_sample(self) -> np.ndarray: ...
    def get_entering_samples(self, time: int) -> np.ndarray: ...
    def get_oud_transition_rates(self) -> np.ndarray: ...
    def get_intervention_transition_rates(self, time: int) -> np.ndarray: ...
    def get_overdose_rtes(self, time: int) -> np.ndarray: ...
    def get_fatal_overdose_rates(self, time: int) -> np.ndarray: ...
    def get_mortality_rates(self) -> np.ndarray: ...
    def get_intervention_init_rates(self) -> np.ndarray: ...
    def set_initial_sample(self, sample: np.ndarray) -> None: ...
    def set_entering_samples(self, samples: dict[int, np.ndarray]) -> None: ...
    def set_oud_transition_rates(self, sample: np.ndarray) -> None: ...
    def set_intervention_transition_rates(
        self, samples: dict[int, np.ndarray]) -> None: ...

    def set_overdose_rates(self, samples: dict[int, np.ndarray]) -> None: ...
    def set_fatal_overdose_rates(
        self, samples: dict[int, np.ndarray]) -> None: ...

    def set_mortality_rates(self, sample: np.ndarray) -> None: ...
    def set_intervention_init_rates(self, sample: np.ndarray) -> None: ...
    def load_initial_sample(self, file: str) -> np.ndarray: ...
    def load_entering_samples(
        self, file: str, intervention: str, behavior: str) -> dict[int, np.ndarray]: ...

    def load_oud_transition_rates(self, file: str) -> np.ndarray: ...
    def load_intervention_init_rates(self, file: str) -> np.ndarray: ...

    def load_intervention_transition_rates(
        self, file: str) -> dict[int, np.ndarray]: ...

    def load_overdose_rates(self, file: str) -> dict[int, np.ndarray]: ...

    def load_fatal_overdose_rates(
        self, file: str) -> dict[int, np.ndarray]: ...

    def load_mortality_rates(
        self, smr_file: str, bg_file: str) -> np.ndarray: ...


class Totals:
    def __init__(self) -> None: ...
    @property
    def base_costs(self) -> list[float]: ...
    @property
    def disc_costs(self) -> list[float]: ...
    @property
    def base_life_years(self) -> float: ...
    @property
    def disc_life_years(self) -> float: ...
    @property
    def base_utility(self) -> float: ...
    @property
    def disc_utility(self) -> float: ...


class UtilityLoader:
    def __init__(self, directory: str, log_name: str) -> None: ...
    def load_background_utility(self, file: str) -> dict[str, np.ndarray]: ...
    def load_oud_utility(self, file: str) -> dict[str, np.ndarray]: ...
    def load_setting_utility(self, file: str) -> dict[str, np.ndarray]: ...
    def get_background_utility(self, perspective: str) -> np.ndarray: ...
    def get_oud_utility(self, perspective: str) -> np.ndarray: ...
    def get_setting_utility(self, perspective: str) -> np.ndarray: ...


class Writer:
    def __init__(self, directory: str, log_name: str) -> None: ...

    def write_input_data(self, data_loader: DataLoader,
                         directory: str, output_type: OutputType) -> str: ...

    def write_history_data(self, history: History,
                           directory: str, output_type: OutputType) -> str: ...

    def write_cost_data(
        self, cost_list: list[Cost], directory: str, output_type: OutputType) -> str: ...

    def write_utility_data(
        self, utilities: dict[int, np.ndarray], directory: str, output_type: OutputType) -> str: ...

    def write_totals_data(self, totals: Totals, directory: str,
                          output_type: OutputType) -> str: ...
