from __future__ import annotations
import numpy
import numpy.typing
import respondpy._core.history
import respondpy._core.model
import typing
__all__: list[str] = ['Simulation']
class Simulation:
    @staticmethod
    def create_default_histories(arg0: str) -> dict[str, respondpy._core.history.History]:
        ...
    def __copy__(self) -> Simulation:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: str) -> None:
        ...
    def __repr__(self) -> str:
        ...
    def add_model(self, arg0: respondpy._core.model.Model) -> None:
        ...
    def clear_models(self) -> None:
        ...
    def get_log_name(self) -> str:
        ...
    def get_model_histories(self) -> dict[str, dict[str, list[typing.Annotated[numpy.typing.NDArray[numpy.float64], "[m, 1]"]]]]:
        ...
    def get_model_history_names(self) -> list[tuple[str, str]]:
        ...
    def get_model_names(self) -> list[str]:
        ...
    def get_models(self) -> list[respondpy._core.model.Model]:
        ...
    def run(self, arg0: typing.SupportsInt) -> None:
        ...
